version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_c
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: realworld_nestjs_typeorm_clone
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  backend:
    build: .
    container_name: conduit_c
    ports:
      - "3000:3000"
    depends_on:
      - db
